# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib pawsdocs _pawsdocs_add_r_to_fences
#' @importFrom Rcpp evalCpp
add_r_to_fences <- function(path, out = "") {
    .Call('_pawsdocs_add_r_to_fences', PACKAGE = 'pawsdocs', path, out)
}

