name: Regenerate Paws Website

on:
  schedule:
    # At 12:00, on day 10 of the month, every 4 months
    # Giving 10 days for paws regen to be approved
    - cron: "0 12 10 */4 *"
  workflow_dispatch:
    inputs:
      text_to_print:
        description: "Manual re-build"

jobs:
  setup:
    runs-on: ubuntu-latest
    name: regen-site

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: "3.9.0.2"

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
        with:
          version: "latest"
          python-version: "3.14"

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev libgit2-dev
          sudo apt-get install -y libharfbuzz-dev libfribidi-dev

      - name: Update Paws Submodule
        run: |
          make update-deps


      - name: Get requirements
        run: make requirements


      - name: Clean Up
        run:
          make clean-down

      - name: Regen Paws Site
        run: |
          make regen-site

      - name: Push to Website AWS S3
        run: |
          echo $GITHUB_REPOSITORY
          if [[ "$GITHUB_REPOSITORY" == "paws-r/paws-r.github.io" ]]; then
            uv run aws s3 sync build/mkdocs/site ${{ secrets.S3FOLDER }} --delete --quiet
          fi

      - name: Force CloudFront to update
        run: |
          if [[ "$GITHUB_REPOSITORY" == "paws-r/paws-r.github.io" ]]; then
            uv run aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION }} --paths "/*" 2>&1 > /dev/null
          fi

      - name: Update docs
        run: |
          mv build/mkdocs/site docs/

      - name: Commit and push changes.
        run: |
          if git diff --quiet && git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git config --global user.name github-actions
            git config --global user.email actions@github.com
            git add .
            git commit -m "Regenerate Paws Website"
            git push -u origin main
          fi